/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from "@tanstack/react-router"

// Import Routes

import { Route as rootRoute } from "./routes/__root"
import { Route as LayoutImport } from "./routes/_layout"
import { Route as LayoutIndexImport } from "./routes/_layout/index"
import { Route as HotelRegisterHotelRegisterLayoutImport } from "./routes/hotel-register/_hotel-register-layout"
import { Route as AuthAuthLayoutImport } from "./routes/auth/_auth-layout"
import { Route as LayoutRoomsImport } from "./routes/_layout/rooms"
import { Route as LayoutOrdersImport } from "./routes/_layout/orders"
import { Route as LayoutAvailabilityPricesImport } from "./routes/_layout/availability-prices"
import { Route as HotelRegisterHotelRegisterLayoutIndexImport } from "./routes/hotel-register/_hotel-register-layout/index"
import { Route as AuthAuthLayoutRegisterImport } from "./routes/auth/_auth-layout/register"
import { Route as AuthAuthLayoutLoginImport } from "./routes/auth/_auth-layout/login"
import { Route as LayoutPaymentsPaymentsLayoutImport } from "./routes/_layout/payments/_payments-layout"
import { Route as LayoutHotelHotelLayoutImport } from "./routes/_layout/hotel/_hotel-layout"
import { Route as LayoutPaymentsPaymentsLayoutIndexImport } from "./routes/_layout/payments/_payments-layout/index"
import { Route as LayoutHotelHotelLayoutIndexImport } from "./routes/_layout/hotel/_hotel-layout/index"
import { Route as LayoutHotelHotelLayoutRulesImport } from "./routes/_layout/hotel/_hotel-layout/rules"
import { Route as LayoutHotelHotelLayoutReviewsImport } from "./routes/_layout/hotel/_hotel-layout/reviews"
import { Route as LayoutHotelHotelLayoutAmenitiesImport } from "./routes/_layout/hotel/_hotel-layout/amenities"

// Create Virtual Routes

const HotelRegisterImport = createFileRoute("/hotel-register")()
const AuthImport = createFileRoute("/auth")()
const LayoutPaymentsImport = createFileRoute("/_layout/payments")()
const LayoutHotelImport = createFileRoute("/_layout/hotel")()

// Create/Update Routes

const HotelRegisterRoute = HotelRegisterImport.update({
  id: "/hotel-register",
  path: "/hotel-register",
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: "/auth",
  path: "/auth",
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: "/_layout",
  getParentRoute: () => rootRoute,
} as any)

const LayoutPaymentsRoute = LayoutPaymentsImport.update({
  id: "/payments",
  path: "/payments",
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutHotelRoute = LayoutHotelImport.update({
  id: "/hotel",
  path: "/hotel",
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => LayoutRoute,
} as any)

const HotelRegisterHotelRegisterLayoutRoute =
  HotelRegisterHotelRegisterLayoutImport.update({
    id: "/_hotel-register-layout",
    getParentRoute: () => HotelRegisterRoute,
  } as any)

const AuthAuthLayoutRoute = AuthAuthLayoutImport.update({
  id: "/_auth-layout",
  getParentRoute: () => AuthRoute,
} as any)

const LayoutRoomsRoute = LayoutRoomsImport.update({
  id: "/rooms",
  path: "/rooms",
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutOrdersRoute = LayoutOrdersImport.update({
  id: "/orders",
  path: "/orders",
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAvailabilityPricesRoute = LayoutAvailabilityPricesImport.update({
  id: "/availability-prices",
  path: "/availability-prices",
  getParentRoute: () => LayoutRoute,
} as any)

const HotelRegisterHotelRegisterLayoutIndexRoute =
  HotelRegisterHotelRegisterLayoutIndexImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => HotelRegisterHotelRegisterLayoutRoute,
  } as any)

const AuthAuthLayoutRegisterRoute = AuthAuthLayoutRegisterImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => AuthAuthLayoutRoute,
} as any)

const AuthAuthLayoutLoginRoute = AuthAuthLayoutLoginImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => AuthAuthLayoutRoute,
} as any)

const LayoutPaymentsPaymentsLayoutRoute =
  LayoutPaymentsPaymentsLayoutImport.update({
    id: "/_payments-layout",
    getParentRoute: () => LayoutPaymentsRoute,
  } as any)

const LayoutHotelHotelLayoutRoute = LayoutHotelHotelLayoutImport.update({
  id: "/_hotel-layout",
  getParentRoute: () => LayoutHotelRoute,
} as any)

const LayoutPaymentsPaymentsLayoutIndexRoute =
  LayoutPaymentsPaymentsLayoutIndexImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => LayoutPaymentsPaymentsLayoutRoute,
  } as any)

const LayoutHotelHotelLayoutIndexRoute =
  LayoutHotelHotelLayoutIndexImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => LayoutHotelHotelLayoutRoute,
  } as any)

const LayoutHotelHotelLayoutRulesRoute =
  LayoutHotelHotelLayoutRulesImport.update({
    id: "/rules",
    path: "/rules",
    getParentRoute: () => LayoutHotelHotelLayoutRoute,
  } as any)

const LayoutHotelHotelLayoutReviewsRoute =
  LayoutHotelHotelLayoutReviewsImport.update({
    id: "/reviews",
    path: "/reviews",
    getParentRoute: () => LayoutHotelHotelLayoutRoute,
  } as any)

const LayoutHotelHotelLayoutAmenitiesRoute =
  LayoutHotelHotelLayoutAmenitiesImport.update({
    id: "/amenities",
    path: "/amenities",
    getParentRoute: () => LayoutHotelHotelLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_layout": {
      id: "/_layout"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    "/_layout/availability-prices": {
      id: "/_layout/availability-prices"
      path: "/availability-prices"
      fullPath: "/availability-prices"
      preLoaderRoute: typeof LayoutAvailabilityPricesImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/orders": {
      id: "/_layout/orders"
      path: "/orders"
      fullPath: "/orders"
      preLoaderRoute: typeof LayoutOrdersImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/rooms": {
      id: "/_layout/rooms"
      path: "/rooms"
      fullPath: "/rooms"
      preLoaderRoute: typeof LayoutRoomsImport
      parentRoute: typeof LayoutImport
    }
    "/auth": {
      id: "/auth"
      path: "/auth"
      fullPath: "/auth"
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    "/auth/_auth-layout": {
      id: "/auth/_auth-layout"
      path: "/auth"
      fullPath: "/auth"
      preLoaderRoute: typeof AuthAuthLayoutImport
      parentRoute: typeof AuthRoute
    }
    "/hotel-register": {
      id: "/hotel-register"
      path: "/hotel-register"
      fullPath: "/hotel-register"
      preLoaderRoute: typeof HotelRegisterImport
      parentRoute: typeof rootRoute
    }
    "/hotel-register/_hotel-register-layout": {
      id: "/hotel-register/_hotel-register-layout"
      path: "/hotel-register"
      fullPath: "/hotel-register"
      preLoaderRoute: typeof HotelRegisterHotelRegisterLayoutImport
      parentRoute: typeof HotelRegisterRoute
    }
    "/_layout/": {
      id: "/_layout/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/hotel": {
      id: "/_layout/hotel"
      path: "/hotel"
      fullPath: "/hotel"
      preLoaderRoute: typeof LayoutHotelImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/hotel/_hotel-layout": {
      id: "/_layout/hotel/_hotel-layout"
      path: "/hotel"
      fullPath: "/hotel"
      preLoaderRoute: typeof LayoutHotelHotelLayoutImport
      parentRoute: typeof LayoutHotelRoute
    }
    "/_layout/payments": {
      id: "/_layout/payments"
      path: "/payments"
      fullPath: "/payments"
      preLoaderRoute: typeof LayoutPaymentsImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/payments/_payments-layout": {
      id: "/_layout/payments/_payments-layout"
      path: "/payments"
      fullPath: "/payments"
      preLoaderRoute: typeof LayoutPaymentsPaymentsLayoutImport
      parentRoute: typeof LayoutPaymentsRoute
    }
    "/auth/_auth-layout/login": {
      id: "/auth/_auth-layout/login"
      path: "/login"
      fullPath: "/auth/login"
      preLoaderRoute: typeof AuthAuthLayoutLoginImport
      parentRoute: typeof AuthAuthLayoutImport
    }
    "/auth/_auth-layout/register": {
      id: "/auth/_auth-layout/register"
      path: "/register"
      fullPath: "/auth/register"
      preLoaderRoute: typeof AuthAuthLayoutRegisterImport
      parentRoute: typeof AuthAuthLayoutImport
    }
    "/hotel-register/_hotel-register-layout/": {
      id: "/hotel-register/_hotel-register-layout/"
      path: "/"
      fullPath: "/hotel-register/"
      preLoaderRoute: typeof HotelRegisterHotelRegisterLayoutIndexImport
      parentRoute: typeof HotelRegisterHotelRegisterLayoutImport
    }
    "/_layout/hotel/_hotel-layout/amenities": {
      id: "/_layout/hotel/_hotel-layout/amenities"
      path: "/amenities"
      fullPath: "/hotel/amenities"
      preLoaderRoute: typeof LayoutHotelHotelLayoutAmenitiesImport
      parentRoute: typeof LayoutHotelHotelLayoutImport
    }
    "/_layout/hotel/_hotel-layout/reviews": {
      id: "/_layout/hotel/_hotel-layout/reviews"
      path: "/reviews"
      fullPath: "/hotel/reviews"
      preLoaderRoute: typeof LayoutHotelHotelLayoutReviewsImport
      parentRoute: typeof LayoutHotelHotelLayoutImport
    }
    "/_layout/hotel/_hotel-layout/rules": {
      id: "/_layout/hotel/_hotel-layout/rules"
      path: "/rules"
      fullPath: "/hotel/rules"
      preLoaderRoute: typeof LayoutHotelHotelLayoutRulesImport
      parentRoute: typeof LayoutHotelHotelLayoutImport
    }
    "/_layout/hotel/_hotel-layout/": {
      id: "/_layout/hotel/_hotel-layout/"
      path: "/"
      fullPath: "/hotel/"
      preLoaderRoute: typeof LayoutHotelHotelLayoutIndexImport
      parentRoute: typeof LayoutHotelHotelLayoutImport
    }
    "/_layout/payments/_payments-layout/": {
      id: "/_layout/payments/_payments-layout/"
      path: "/"
      fullPath: "/payments/"
      preLoaderRoute: typeof LayoutPaymentsPaymentsLayoutIndexImport
      parentRoute: typeof LayoutPaymentsPaymentsLayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutHotelHotelLayoutRouteChildren {
  LayoutHotelHotelLayoutAmenitiesRoute: typeof LayoutHotelHotelLayoutAmenitiesRoute
  LayoutHotelHotelLayoutReviewsRoute: typeof LayoutHotelHotelLayoutReviewsRoute
  LayoutHotelHotelLayoutRulesRoute: typeof LayoutHotelHotelLayoutRulesRoute
  LayoutHotelHotelLayoutIndexRoute: typeof LayoutHotelHotelLayoutIndexRoute
}

const LayoutHotelHotelLayoutRouteChildren: LayoutHotelHotelLayoutRouteChildren =
  {
    LayoutHotelHotelLayoutAmenitiesRoute: LayoutHotelHotelLayoutAmenitiesRoute,
    LayoutHotelHotelLayoutReviewsRoute: LayoutHotelHotelLayoutReviewsRoute,
    LayoutHotelHotelLayoutRulesRoute: LayoutHotelHotelLayoutRulesRoute,
    LayoutHotelHotelLayoutIndexRoute: LayoutHotelHotelLayoutIndexRoute,
  }

const LayoutHotelHotelLayoutRouteWithChildren =
  LayoutHotelHotelLayoutRoute._addFileChildren(
    LayoutHotelHotelLayoutRouteChildren,
  )

interface LayoutHotelRouteChildren {
  LayoutHotelHotelLayoutRoute: typeof LayoutHotelHotelLayoutRouteWithChildren
}

const LayoutHotelRouteChildren: LayoutHotelRouteChildren = {
  LayoutHotelHotelLayoutRoute: LayoutHotelHotelLayoutRouteWithChildren,
}

const LayoutHotelRouteWithChildren = LayoutHotelRoute._addFileChildren(
  LayoutHotelRouteChildren,
)

interface LayoutPaymentsPaymentsLayoutRouteChildren {
  LayoutPaymentsPaymentsLayoutIndexRoute: typeof LayoutPaymentsPaymentsLayoutIndexRoute
}

const LayoutPaymentsPaymentsLayoutRouteChildren: LayoutPaymentsPaymentsLayoutRouteChildren =
  {
    LayoutPaymentsPaymentsLayoutIndexRoute:
      LayoutPaymentsPaymentsLayoutIndexRoute,
  }

const LayoutPaymentsPaymentsLayoutRouteWithChildren =
  LayoutPaymentsPaymentsLayoutRoute._addFileChildren(
    LayoutPaymentsPaymentsLayoutRouteChildren,
  )

interface LayoutPaymentsRouteChildren {
  LayoutPaymentsPaymentsLayoutRoute: typeof LayoutPaymentsPaymentsLayoutRouteWithChildren
}

const LayoutPaymentsRouteChildren: LayoutPaymentsRouteChildren = {
  LayoutPaymentsPaymentsLayoutRoute:
    LayoutPaymentsPaymentsLayoutRouteWithChildren,
}

const LayoutPaymentsRouteWithChildren = LayoutPaymentsRoute._addFileChildren(
  LayoutPaymentsRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAvailabilityPricesRoute: typeof LayoutAvailabilityPricesRoute
  LayoutOrdersRoute: typeof LayoutOrdersRoute
  LayoutRoomsRoute: typeof LayoutRoomsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutHotelRoute: typeof LayoutHotelRouteWithChildren
  LayoutPaymentsRoute: typeof LayoutPaymentsRouteWithChildren
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAvailabilityPricesRoute: LayoutAvailabilityPricesRoute,
  LayoutOrdersRoute: LayoutOrdersRoute,
  LayoutRoomsRoute: LayoutRoomsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutHotelRoute: LayoutHotelRouteWithChildren,
  LayoutPaymentsRoute: LayoutPaymentsRouteWithChildren,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface AuthAuthLayoutRouteChildren {
  AuthAuthLayoutLoginRoute: typeof AuthAuthLayoutLoginRoute
  AuthAuthLayoutRegisterRoute: typeof AuthAuthLayoutRegisterRoute
}

const AuthAuthLayoutRouteChildren: AuthAuthLayoutRouteChildren = {
  AuthAuthLayoutLoginRoute: AuthAuthLayoutLoginRoute,
  AuthAuthLayoutRegisterRoute: AuthAuthLayoutRegisterRoute,
}

const AuthAuthLayoutRouteWithChildren = AuthAuthLayoutRoute._addFileChildren(
  AuthAuthLayoutRouteChildren,
)

interface AuthRouteChildren {
  AuthAuthLayoutRoute: typeof AuthAuthLayoutRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAuthLayoutRoute: AuthAuthLayoutRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface HotelRegisterHotelRegisterLayoutRouteChildren {
  HotelRegisterHotelRegisterLayoutIndexRoute: typeof HotelRegisterHotelRegisterLayoutIndexRoute
}

const HotelRegisterHotelRegisterLayoutRouteChildren: HotelRegisterHotelRegisterLayoutRouteChildren =
  {
    HotelRegisterHotelRegisterLayoutIndexRoute:
      HotelRegisterHotelRegisterLayoutIndexRoute,
  }

const HotelRegisterHotelRegisterLayoutRouteWithChildren =
  HotelRegisterHotelRegisterLayoutRoute._addFileChildren(
    HotelRegisterHotelRegisterLayoutRouteChildren,
  )

interface HotelRegisterRouteChildren {
  HotelRegisterHotelRegisterLayoutRoute: typeof HotelRegisterHotelRegisterLayoutRouteWithChildren
}

const HotelRegisterRouteChildren: HotelRegisterRouteChildren = {
  HotelRegisterHotelRegisterLayoutRoute:
    HotelRegisterHotelRegisterLayoutRouteWithChildren,
}

const HotelRegisterRouteWithChildren = HotelRegisterRoute._addFileChildren(
  HotelRegisterRouteChildren,
)

export interface FileRoutesByFullPath {
  "": typeof LayoutRouteWithChildren
  "/availability-prices": typeof LayoutAvailabilityPricesRoute
  "/orders": typeof LayoutOrdersRoute
  "/rooms": typeof LayoutRoomsRoute
  "/auth": typeof AuthAuthLayoutRouteWithChildren
  "/hotel-register": typeof HotelRegisterHotelRegisterLayoutRouteWithChildren
  "/": typeof LayoutIndexRoute
  "/hotel": typeof LayoutHotelHotelLayoutRouteWithChildren
  "/payments": typeof LayoutPaymentsPaymentsLayoutRouteWithChildren
  "/auth/login": typeof AuthAuthLayoutLoginRoute
  "/auth/register": typeof AuthAuthLayoutRegisterRoute
  "/hotel-register/": typeof HotelRegisterHotelRegisterLayoutIndexRoute
  "/hotel/amenities": typeof LayoutHotelHotelLayoutAmenitiesRoute
  "/hotel/reviews": typeof LayoutHotelHotelLayoutReviewsRoute
  "/hotel/rules": typeof LayoutHotelHotelLayoutRulesRoute
  "/hotel/": typeof LayoutHotelHotelLayoutIndexRoute
  "/payments/": typeof LayoutPaymentsPaymentsLayoutIndexRoute
}

export interface FileRoutesByTo {
  "/availability-prices": typeof LayoutAvailabilityPricesRoute
  "/orders": typeof LayoutOrdersRoute
  "/rooms": typeof LayoutRoomsRoute
  "/auth": typeof AuthAuthLayoutRouteWithChildren
  "/hotel-register": typeof HotelRegisterHotelRegisterLayoutIndexRoute
  "/": typeof LayoutIndexRoute
  "/hotel": typeof LayoutHotelHotelLayoutIndexRoute
  "/payments": typeof LayoutPaymentsPaymentsLayoutIndexRoute
  "/auth/login": typeof AuthAuthLayoutLoginRoute
  "/auth/register": typeof AuthAuthLayoutRegisterRoute
  "/hotel/amenities": typeof LayoutHotelHotelLayoutAmenitiesRoute
  "/hotel/reviews": typeof LayoutHotelHotelLayoutReviewsRoute
  "/hotel/rules": typeof LayoutHotelHotelLayoutRulesRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  "/_layout": typeof LayoutRouteWithChildren
  "/_layout/availability-prices": typeof LayoutAvailabilityPricesRoute
  "/_layout/orders": typeof LayoutOrdersRoute
  "/_layout/rooms": typeof LayoutRoomsRoute
  "/auth": typeof AuthRouteWithChildren
  "/auth/_auth-layout": typeof AuthAuthLayoutRouteWithChildren
  "/hotel-register": typeof HotelRegisterRouteWithChildren
  "/hotel-register/_hotel-register-layout": typeof HotelRegisterHotelRegisterLayoutRouteWithChildren
  "/_layout/": typeof LayoutIndexRoute
  "/_layout/hotel": typeof LayoutHotelRouteWithChildren
  "/_layout/hotel/_hotel-layout": typeof LayoutHotelHotelLayoutRouteWithChildren
  "/_layout/payments": typeof LayoutPaymentsRouteWithChildren
  "/_layout/payments/_payments-layout": typeof LayoutPaymentsPaymentsLayoutRouteWithChildren
  "/auth/_auth-layout/login": typeof AuthAuthLayoutLoginRoute
  "/auth/_auth-layout/register": typeof AuthAuthLayoutRegisterRoute
  "/hotel-register/_hotel-register-layout/": typeof HotelRegisterHotelRegisterLayoutIndexRoute
  "/_layout/hotel/_hotel-layout/amenities": typeof LayoutHotelHotelLayoutAmenitiesRoute
  "/_layout/hotel/_hotel-layout/reviews": typeof LayoutHotelHotelLayoutReviewsRoute
  "/_layout/hotel/_hotel-layout/rules": typeof LayoutHotelHotelLayoutRulesRoute
  "/_layout/hotel/_hotel-layout/": typeof LayoutHotelHotelLayoutIndexRoute
  "/_layout/payments/_payments-layout/": typeof LayoutPaymentsPaymentsLayoutIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ""
    | "/availability-prices"
    | "/orders"
    | "/rooms"
    | "/auth"
    | "/hotel-register"
    | "/"
    | "/hotel"
    | "/payments"
    | "/auth/login"
    | "/auth/register"
    | "/hotel-register/"
    | "/hotel/amenities"
    | "/hotel/reviews"
    | "/hotel/rules"
    | "/hotel/"
    | "/payments/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/availability-prices"
    | "/orders"
    | "/rooms"
    | "/auth"
    | "/hotel-register"
    | "/"
    | "/hotel"
    | "/payments"
    | "/auth/login"
    | "/auth/register"
    | "/hotel/amenities"
    | "/hotel/reviews"
    | "/hotel/rules"
  id:
    | "__root__"
    | "/_layout"
    | "/_layout/availability-prices"
    | "/_layout/orders"
    | "/_layout/rooms"
    | "/auth"
    | "/auth/_auth-layout"
    | "/hotel-register"
    | "/hotel-register/_hotel-register-layout"
    | "/_layout/"
    | "/_layout/hotel"
    | "/_layout/hotel/_hotel-layout"
    | "/_layout/payments"
    | "/_layout/payments/_payments-layout"
    | "/auth/_auth-layout/login"
    | "/auth/_auth-layout/register"
    | "/hotel-register/_hotel-register-layout/"
    | "/_layout/hotel/_hotel-layout/amenities"
    | "/_layout/hotel/_hotel-layout/reviews"
    | "/_layout/hotel/_hotel-layout/rules"
    | "/_layout/hotel/_hotel-layout/"
    | "/_layout/payments/_payments-layout/"
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  HotelRegisterRoute: typeof HotelRegisterRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  HotelRegisterRoute: HotelRegisterRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout",
        "/auth",
        "/hotel-register"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/availability-prices",
        "/_layout/orders",
        "/_layout/rooms",
        "/_layout/",
        "/_layout/hotel",
        "/_layout/payments"
      ]
    },
    "/_layout/availability-prices": {
      "filePath": "_layout/availability-prices.tsx",
      "parent": "/_layout"
    },
    "/_layout/orders": {
      "filePath": "_layout/orders.tsx",
      "parent": "/_layout"
    },
    "/_layout/rooms": {
      "filePath": "_layout/rooms.tsx",
      "parent": "/_layout"
    },
    "/auth": {
      "filePath": "auth",
      "children": [
        "/auth/_auth-layout"
      ]
    },
    "/auth/_auth-layout": {
      "filePath": "auth/_auth-layout.tsx",
      "parent": "/auth",
      "children": [
        "/auth/_auth-layout/login",
        "/auth/_auth-layout/register"
      ]
    },
    "/hotel-register": {
      "filePath": "hotel-register",
      "children": [
        "/hotel-register/_hotel-register-layout"
      ]
    },
    "/hotel-register/_hotel-register-layout": {
      "filePath": "hotel-register/_hotel-register-layout.tsx",
      "parent": "/hotel-register",
      "children": [
        "/hotel-register/_hotel-register-layout/"
      ]
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/hotel": {
      "filePath": "_layout/hotel",
      "parent": "/_layout",
      "children": [
        "/_layout/hotel/_hotel-layout"
      ]
    },
    "/_layout/hotel/_hotel-layout": {
      "filePath": "_layout/hotel/_hotel-layout.tsx",
      "parent": "/_layout/hotel",
      "children": [
        "/_layout/hotel/_hotel-layout/amenities",
        "/_layout/hotel/_hotel-layout/reviews",
        "/_layout/hotel/_hotel-layout/rules",
        "/_layout/hotel/_hotel-layout/"
      ]
    },
    "/_layout/payments": {
      "filePath": "_layout/payments",
      "parent": "/_layout",
      "children": [
        "/_layout/payments/_payments-layout"
      ]
    },
    "/_layout/payments/_payments-layout": {
      "filePath": "_layout/payments/_payments-layout.tsx",
      "parent": "/_layout/payments",
      "children": [
        "/_layout/payments/_payments-layout/"
      ]
    },
    "/auth/_auth-layout/login": {
      "filePath": "auth/_auth-layout/login.tsx",
      "parent": "/auth/_auth-layout"
    },
    "/auth/_auth-layout/register": {
      "filePath": "auth/_auth-layout/register.tsx",
      "parent": "/auth/_auth-layout"
    },
    "/hotel-register/_hotel-register-layout/": {
      "filePath": "hotel-register/_hotel-register-layout/index.tsx",
      "parent": "/hotel-register/_hotel-register-layout"
    },
    "/_layout/hotel/_hotel-layout/amenities": {
      "filePath": "_layout/hotel/_hotel-layout/amenities.tsx",
      "parent": "/_layout/hotel/_hotel-layout"
    },
    "/_layout/hotel/_hotel-layout/reviews": {
      "filePath": "_layout/hotel/_hotel-layout/reviews.tsx",
      "parent": "/_layout/hotel/_hotel-layout"
    },
    "/_layout/hotel/_hotel-layout/rules": {
      "filePath": "_layout/hotel/_hotel-layout/rules.tsx",
      "parent": "/_layout/hotel/_hotel-layout"
    },
    "/_layout/hotel/_hotel-layout/": {
      "filePath": "_layout/hotel/_hotel-layout/index.tsx",
      "parent": "/_layout/hotel/_hotel-layout"
    },
    "/_layout/payments/_payments-layout/": {
      "filePath": "_layout/payments/_payments-layout/index.tsx",
      "parent": "/_layout/payments/_payments-layout"
    }
  }
}
ROUTE_MANIFEST_END */
